### ISSUE TITLE
E117: unknown function: man#open_page

### ISSUE THREAD

**Issue by sebastianfastert** [bruno-/vim-man#47]
Hello,

I've installed vim-man with vim-plug.
I'm on mac os 10.15.5 using neovim v0.4.3.
When I'm doing `:Man printf` the error `E117: Unbekannte Funktion: man#open_page` comes up.

Thanks for your help.
Sebastian

**Comment by sebastianfastert** [comment]
This is no longer needed. I found a fork specifically for neovim.

**Comment by Sangdol** [comment]
This is the plugin for neovim:
https://github.com/paretje/nvim-man

**Comment by Sangdol** [comment]
You don't even need a plugin for this if you use nvim:
https://neovim.io/doc/user/filetype.html#ft-man-plugin
